# System Settings
site_url: http://cbticket.ddns.net # This is the URL of your support site

# Toggle functionality (not fully implemented)
tickets: true
forums: true
knowledgebase: true
teams: true
welcome_email: true

# Site Settings (These have been moved into the admin UI and you should change them there!)
parent_site: /parent-redirect.html # This tells Helpy how to provide a link back to your main site
parent_company: Main Site # This is the parent company your helpdesk is providing support for
site_name: Helpy Support # This is the name of your support site
site_tagline: Support and Helpdesk Software # This is the tagline of your support site
product_name: # This is the product name your are supporting
support_phone: # This is the support number to be displayed
app_favicon: favicon.ico #Full or partial url for app favicon
app_large_logo: logo.png #Full or partial url app large logo
app_mini_logo: logo.png # Full or partial url for app mini logo

# Analytics and Tracking
google_analytics_id: #Enter your analytics ID
send_usage_data: true

#Recaptcha secret keys
recaptcha_site_key: #Enter your site key
recaptcha_api_key: #Enter your api  key

# Mail specific settings:
# See http://support.helpy.io/en/knowledgebase/11-Installing-Helpy/docs/14-Setting-up-your-Helpy-installation-to-send-and-receive-email

admin_email: brightlight@cahayabangsa.org
from_email: brightlight@cahayabangsa.org # This is the email that will be used for email replies (reply to)
send_email: true #Send email or not

mail_service: :mailgun # :sendgrid :cloudmailin, :postmark, :mandrill, :mailgun, :sparkpost
smtp_mail_username: <%= ENV['SMTP_MAIL_USERNAME'] %>
smtp_mail_password: <%= ENV['SMTP_MAIL_PASSWORD'] %>
mail_smtp: 'smtp.gmail.com' #Enter the server address for your SMTP server
mail_port: 587 #Enter the port of your SMTP server
mail_domain: 'cahayabangsa.org'

# Omniauth Config
# You must sign up with each oauth provider you wish to support, uncomment and add the ID and secret
# for each below.  See http://support.helpy.io/en/knowledgebase/11-Installing-Helpy/docs/19-Setting-Up-OAUTH-for-your-Helpy

omniauth:
  providers:
#    github:
#      id:
#      secret:
#    twitter:
#      id:
#      secret:
    google_oauth2:
      id: <%= ENV['GOOGLE_CLIENT_ID'] %>
      secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
      whitelisted_domains: "cahayabangsa.org"
